## default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 60000
      maximumPoolSize: 5
    url: jdbc:postgresql://nikkapowerappdb.cuqxn47cqupl.ap-south-1.rds.amazonaws.com:5432/nikkapowerappdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: service
server:
  port: 5000

#truncate table table_name restart identity;
